services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  giropops-web:
    depends_on:
      - redis
    image: psazevedo/linuxtips-giropops-senhas:1.0
    container_name: giropops-senhas
    hostname: giropops-senhas
    ports:
      - "80:5000"
    environment:
      - REDIS_HOST=redis
    
networks: 
  giropops:
    driver: bridge